//numeros 
const numero1=100+15*3; //multiplica primero 15*3 y luego le suma 100
const numero2=200*2; //las multiplicaciones y divisiones tienen mas peso que las sumas 
const numero3=200/2;
const numero4= 100;

console.log(numero1 + numero2)
console.log(numero2 + numero4 )
console.log(numero2 % numero4) //retorna el resto de la division 
console.log(numero3)
console.log(numero4)

//objeto math

let resultado;
let valor;
valor=Math.min(5, 5, 8, 8, 9, 4,);
resultado=Math.PI; 
resultado=Math.round(2.6); //redondea
resultado=Math.ceil(2.2); //redondea siempre hacia arriba 
resultado=Math.floor(5.9); //redondea hacia abajo. la ultima variable es la que se asigna




console.log(resultado)

//incrementos

let puntaje=10;//incremento en 1
puntaje ++; 
puntaje--; // Decrece en 1

console.log(puntaje);

